(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},m=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ba="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var q;a:{var ca={a:!0},u={};try{u.__proto__=ca;q=u.a;break a}catch(a){}q=!1}n=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var v=n,da=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},w=da(this),ea="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},fa=function(a,b){if(b){var c=w;a=a.split(".");for(var e=0;e<a.length-1;e++){var g=
a[e];g in c||(c[g]={});c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&ea(c,a,{configurable:!0,writable:!0,value:b})}};
fa("Promise",function(a){function b(){this.j=null}function c(d){return d instanceof g?d:new g(function(f){f(d)})}if(a)return a;b.prototype.C=function(d){if(null==this.j){this.j=[];var f=this;this.D(function(){f.P()})}this.j.push(d)};var e=w.setTimeout;b.prototype.D=function(d){e(d,0)};b.prototype.P=function(){for(;this.j&&this.j.length;){var d=this.j;this.j=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(l){this.O(l)}}}this.j=null};b.prototype.O=function(d){this.D(function(){throw d;
})};var g=function(d){this.o=0;this.B=void 0;this.m=[];var f=this.v();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};g.prototype.v=function(){function d(l){return function(p){h||(h=!0,l.call(f,p))}}var f=this,h=!1;return{resolve:d(this.V),reject:d(this.A)}};g.prototype.V=function(d){if(d===this)this.A(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof g)this.W(d);else{a:switch(typeof d){case "object":var f=null!=d;break a;case "function":f=!0;break a;default:f=!1}f?this.U(d):
this.G(d)}};g.prototype.U=function(d){var f=void 0;try{f=d.then}catch(h){this.A(h);return}"function"==typeof f?this.$(f,d):this.G(d)};g.prototype.A=function(d){this.N(2,d)};g.prototype.G=function(d){this.N(1,d)};g.prototype.N=function(d,f){if(0!=this.o)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.o);this.o=d;this.B=f;this.R()};g.prototype.R=function(){if(null!=this.m){for(var d=0;d<this.m.length;++d)T.C(this.m[d]);this.m=null}};var T=new b;g.prototype.W=function(d){var f=
this.v();d.s(f.resolve,f.reject)};g.prototype.$=function(d,f){var h=this.v();try{d.call(f,h.resolve,h.reject)}catch(l){h.reject(l)}};g.prototype.then=function(d,f){function h(r,t){return"function"==typeof r?function(E){try{l(r(E))}catch(F){p(F)}}:t}var l,p,G=new g(function(r,t){l=r;p=t});this.s(h(d,l),h(f,p));return G};g.prototype.catch=function(d){return this.then(void 0,d)};g.prototype.s=function(d,f){function h(){switch(l.o){case 1:d(l.B);break;case 2:f(l.B);break;default:throw Error("Unexpected state: "+
l.o);}}var l=this;null==this.m?T.C(h):this.m.push(h)};g.resolve=c;g.reject=function(d){return new g(function(f,h){h(d)})};g.race=function(d){return new g(function(f,h){for(var l=m(d),p=l.next();!p.done;p=l.next())c(p.value).s(f,h)})};g.all=function(d){var f=m(d),h=f.next();return h.done?c([]):new g(function(l,p){function G(E){return function(F){r[E]=F;t--;0==t&&l(r)}}var r=[],t=0;do r.push(void 0),t++,c(h.value).s(G(r.length-1),p),h=f.next();while(!h.done)})};return g});
var x=this||self,ha=Date.now||function(){return+new Date},y=function(a,b){a=a.split(".");var c=x;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?c=c[e]&&c[e]!==Object.prototype[e]?c[e]:c[e]={}:c[e]=b};var z=function(){this.K=""};z.prototype.toString=function(){return"SafeScript{"+this.K+"}"};z.prototype.i=function(a){this.K=a};(new z).i("");var A=function(){this.M=""};A.prototype.toString=function(){return"SafeStyle{"+this.M+"}"};A.prototype.i=function(a){this.M=a};(new A).i("");var B=function(){this.L=""};B.prototype.toString=function(){return"SafeStyleSheet{"+this.L+"}"};B.prototype.i=function(a){this.L=a};(new B).i("");var C=function(){this.J=""};C.prototype.toString=function(){return"SafeHtml{"+this.J+"}"};C.prototype.i=function(a){this.J=a};(new C).i("<!DOCTYPE html>");(new C).i("");(new C).i("<br>");Object.freeze&&Object.freeze([]);try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var D=function(a,b){var c=(c=x.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):ha();a={label:a,type:9,value:c};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var H={},I=!1,J=!1;H.S=function(a){I||(I=!0,D("11",a))};H.T=function(a){J||(J=!0,D("12",a))};H.I=function(a,b,c){var e=b;e=void 0===e?x:e;if(e=(e=e.performance)&&e.now?e.now():null)a={label:a,type:void 0===c?0:c,value:e},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};H.reset=function(a){J=I=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};y("gwd.rumUtil",H);y("gwd.rumUtil.logContentLoading",H.S);
y("gwd.rumUtil.logContentRendered",H.T);y("gwd.rumUtil.logTimingEvent",H.I);y("gwd.rumUtil.reset",H.reset);var K=function(a){(0,H.I)("gwd3dmodel_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame")},M=function(a){a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement");L()},N=0,O=0;function L(){var a=Math.floor(performance.now()/100);0==N&&(N=a);for(a-=N;O<=a;O++)Enabler.counter("TotalSessionDurationDeciseconds",!0)}
var P={Engagement:function(){Enabler.reportEngagement()},Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}},
ia={};var Q=function(a,b,c){c=void 0===c?null:c;var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c);b.dispatchEvent(e)};var ja=["glass","gesture-cue-icon","gesture-cue-text","src","transparent"],R=function(){var a=HTMLElement.call(this)||this;a.h=null;a.u=!1;return a},S=HTMLElement;R.prototype=ba(S.prototype);R.prototype.constructor=R;if(v)v(R,S);else for(var U in S)if("prototype"!=U)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(S,U);V&&Object.defineProperty(R,U,V)}else R[U]=S[U];
R.prototype.connectedCallback=function(){window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));W(this)};
R.prototype.disconnectedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.l&&(clearTimeout(this.l),this.l=void 0)};R.prototype.attributeChangedCallback=function(){W(this)};
R.prototype.handleEvent=function(a){var b=this,c=a.type,e=a.detail;switch(c){case "click":(this.H||this.F)&&a.target===this.f&&a.stopPropagation();break;case "start-timer":case "stop-timer":ka(this,e.timer,"start-timer"===c);break;case "scene-rendered":case "camera-changed":a.stopPropagation();Q(c,this,e);break;case "hotspot-clicked":this.F=!0;window.setTimeout(function(){b.F=!1},0);la(e.index);a.stopPropagation();Q(c,this,e);break;case "increment-counter":ma(e.counter,e.cumulative);break;case studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH:X(this).removeAttribute("scroll-gating");
Enabler.reportEngagement();L();break;case studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH:X(this).setAttribute("scroll-gating",""),L()}};
var X=function(a){a.f||(a.f=a.ownerDocument.createElement("gltf-viewer"),a.f.setAttribute("scroll-gating",""),a.f.addEventListener("start-timer",a),a.f.addEventListener("stop-timer",a),a.f.addEventListener("increment-counter",a),a.f.addEventListener("scene-rendered",a),a.f.addEventListener("camera-changed",a),a.f.addEventListener("hotspot-clicked",a),a.f.addEventListener("click",a),a.appendChild(a.f));return a.f},W=function(a){a.l||(a.l=window.setTimeout(a.gwdLoad.bind(a),0))};
R.prototype.gwdLoad=function(){this.l&&(clearTimeout(this.l),this.l=void 0);var a=this.f?this.f.getAttribute("src"):null,b=Y(this,"src",!0);if(b){if(Y(this,"transparent"),Y(this,"glass"),b!==a&&(this.u=!1,this.classList.remove("ready"),K(!0)),this.h&&this.h.parentNode&&this.h.parentNode.removeChild(this.h),b=this.getAttribute("gesture-cue-icon")){this.h=this.ownerDocument.createElement("div");this.h.classList.add("gesture-cue-container");a=this.ownerDocument.createElement("div");a.classList.add("gesture-cue-icon");
a.style.backgroundImage='url("'+b+'")';b=parseFloat(this.getAttribute("gesture-cue-duration"));isFinite(b)||(b=29);a.style.animationIterationCount=0>b?"infinite, 1":(b/2).toFixed(1)+", 1";this.h.appendChild(a);if(a=this.getAttribute("gesture-cue-text"))b=this.ownerDocument.createElement("p"),b.classList.add("gesture-cue-text"),b.textContent=a,this.h.appendChild(b);this.appendChild(this.h)}}else na(this)};R.prototype.gwdIsLoaded=function(){return this.u};
var Y=function(a,b,c){c=void 0===c?!1:c;var e=a.getAttribute(b);null==e||c&&!e?a.f&&a.f.removeAttribute(b):X(a).setAttribute(b,e);return a.f?a.f.getAttribute(b):null},na=function(a){a.u||(a.u=!0,Q("ready",a))},ka=function(a,b,c){c?"TotalEngagement"===b&&(a.H=!0,M(!0),Q("interaction-start",a),a.h&&a.h.parentNode&&a.h.parentNode.removeChild(a.h)):"TotalEngagement"===b?(a.H=!1,M(!1),Q("interaction-end",a)):"TimeToFirstFrame"===b&&(K(!1),a.classList.add("ready"),na(a))},ma=function(a,b){b=b?P:ia;if(b[a])b[a]()},
la=function(a){P.Engagement();a="Hotspot"+(a+1)+"Click";if(P[a])P[a]()};k=R.prototype;k.setYaw=function(a){Z(this,{name:"setYaw",yawAngle:a,pauseRestingAnimation:!0})};k.setTargetYaw=function(a){Z(this,{name:"setTargetYaw",yawAngle:a})};k.setTargetPitch=function(a){Z(this,{name:"setTargetPitch",pitchAngle:a})};k.incrementTargetPitch=function(a){Z(this,{name:"incrementTargetPitch",pitchAngle:a})};k.setTargetZoom=function(a){Z(this,{name:"setTargetZoom",scale:a})};
k.incrementTargetZoom=function(a){Z(this,{name:"incrementTargetZoom",scale:a})};k.setTargetPivot=function(a,b,c){Z(this,{name:"setTargetPivot",X:a,Y:b,Z:c})};k.setTargetLocalPan=function(a,b){Z(this,{name:"setTargetLocalPan",X:a,Y:b})};k.setMaterialColor=function(a,b,c,e){Z(this,{name:"setMaterialColor",material:a,r:b,g:c,b:e})};k.setMaterialClearCoat=function(a,b,c){Z(this,{name:"setMaterialClearCoat",material:a,value:b,roughness:c})};k.playAnimation=function(a){Z(this,{name:"animationPlay",animationName:a})};
k.pauseAnimation=function(a){Z(this,{name:"animationPause",animationName:a})};k.setAnimationTime=function(a,b){Z(this,{name:"animationSetTime",animationName:a,time:b})};k.incrementAnimationTime=function(a,b){Z(this,{name:"animationIncrementTime",animationName:a,time:b})};k.addHotspot=function(a,b,c,e){Z(this,{name:"addHotspot",hotspotName:a,x:b,y:c,z:e})};k.setHotspotInfoCard=function(a,b,c){Z(this,{name:"setHotspotInfoCard",hotspotName:a,title:b,text:c})};
k.lookAtHotspot=function(a){Z(this,{name:"lookAtHotspot",hotspotName:a})};k.lookAtHotspotIndex=function(a){Z(this,{name:"lookAtHotspotIndex",hotspotIndex:a})};k.handleMessage=function(a){Z(this,a)};var Z=function(a,b){a=X(a);a.handleMessage&&a.handleMessage(b)};w.Object.defineProperties(R,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ja}}});customElements.define("gwd-3d-model",R);}).call(this);
